
on:
  schedule:
    - cron: 0 0,15,23 * * *
  push:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - run: sudo apt-get -qq update && sudo apt-get -yqq install --no-install-recommends ffmpeg fonts-noto-cjk
      - run: yarn add puppeteer
      - run: node main.mjs
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          PROXY_SERVER: ${{ secrets.PROXY_SERVER }}
      - uses: actions/upload-artifact@v4
        with:
          path: recording.webm
      - name: Send video to Telegram
        if: always()
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendVideo" \
            -F chat_id="${{ secrets.TG_CHAT_ID }}" \
            -F video=@"recording.webm" \
            -F caption="JPxserver 录制视频"
